name: Docker tags

on:
  push:
    tags:
      - 'y*.*.*'
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF}
      - run: echo ${GITHUB_REF#refs/tags/}
      - run: echo ${GITHUB_REF##*/}
